//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::chat_admins::Entity as ChatAdmins;
pub use super::chats::Entity as Chats;
pub use super::meme_likes::Entity as MemeLikes;
pub use super::memes::Entity as Memes;
pub use super::messages::Entity as Messages;
pub use super::users::Entity as Users;
