[package]
name = "tg_meme_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Telegram Bot Library
teloxide = { version = "0.11", features = ["macros"] }
# Logs Libraries
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
# Env Files Loader
dotenv = "0.15.0"
# Comand-Line Arguments
clap = { version = "4.0.29", features = ["derive"] }
emojis = "0.5.2"
redis = { version = "0.22.1", features = ["tokio-comp", "connection-manager"] }
diesel = { version = "2.0.0", features = ["postgres", "r2d2", "serde_json"] }
futures = "0.3.25"
serde_json = "1.0.89"
derive_builder = "0.12.0"
