FROM medic84/rust-diesel:latest as builder

COPY --from=medic84/opencv:4.8.0 /usr/local/lib/libopencv_* /usr/local/lib/
COPY --from=medic84/opencv:4.8.0 /usr/local/bin/opencv_* /usr/local/bin/
COPY --from=medic84/opencv:4.8.0 /usr/local/include/opencv4 /usr/local/include/opencv4/
COPY --from=medic84/opencv:4.8.0 /usr/local/lib/cmake/opencv4 /usr/local/lib/cmake/opencv4/
COPY --from=medic84/opencv:4.8.0 /usr/local/share/opencv4 /usr/local/share/opencv4/

RUN apt-get update \
    && apt-get install -y cmake build-essential clang pkg-config \
      libavcodec-dev libavformat-dev libswscale-dev libtbb-dev libjpeg-dev libpng-dev libtiff-dev libpq-dev llvm-dev \
      libgtk2.0-dev libdc1394-22-dev libssl-dev \
    && apt-get clean

WORKDIR /app

COPY . /app

RUN cargo build --release

FROM debian:bullseye-slim

ARG BOT_VERSION=unknown
ENV BOT_VERSION=$BOT_VERSION

MAINTAINER "mediclab"
LABEL org.opencontainers.image.authors="mediclab <m@mdlb.cc>"
LABEL version=$BOT_VERSION
LABEL description="Bot for mem-chats"

RUN apt-get update  \
    && apt-get install -y ca-certificates libpq5 libjpeg-dev libpng-dev libopenjp2-7 \
      libtbb2 libtiff5 libwebp6 libopenexr25 libgtk2.0-0 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/tg_meme_bot /usr/local/bin/tg_meme_bot
COPY --from=builder  /usr/local/cargo/bin/diesel /usr/local/bin/diesel
COPY --from=medic84/opencv:4.8.0 /usr/local/lib/libopencv_* /usr/local/lib/
COPY --from=medic84/opencv:4.8.0 /usr/local/bin/opencv_* /usr/local/bin/

WORKDIR /app

COPY ./migrations /app/migrations
COPY ./diesel.toml /app/diesel.toml
COPY ./initd.sh /app/initd.sh

ENV LD_LIBRARY_PATH=/usr/local/lib

RUN chmod +x /app/initd.sh

CMD ["/app/initd.sh"]