FROM rust:slim-bullseye as builder

RUN apt-get update \
    && apt-get install -y cmake build-essential clang pkg-config \
          libavcodec-dev libavformat-dev libswscale-dev libtbb-dev llvm-dev \
          libgtk2.0-dev libdc1394-22-dev libssl-dev libjpeg-dev libpng-dev libtiff-dev libpq-dev \
    && apt-get clean