version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: meme_bot
      POSTGRES_DB: meme_bot
      POSTGRES_PASSWORD: pass_meme_bot
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U meme_bot" ]
      interval: 2s
      timeout: 2s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - 6379:6379
  
  bot:
    build:
      dockerfile: "./Dockerfile"
      context: .
    environment:
      CARGO_HOME: /app/.cargo_home
    command: sh -c "diesel migration run && cargo run -- --start"
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data: