CREATE TABLE IF NOT EXISTS meme_likes (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    meme_id BIGINT NOT NULL,
    num SMALLINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX ON meme_likes (user_id, meme_id);