name: Build Docker Images

on:
  release:
    types: [ published ]

env:
  IMAGE_TITLE: "TG Meme Bot"
  IMAGE_DESCRIPTION: "Bot for mem-chats"
  IMAGE_NAME: "${{ secrets.DOCKER_HOME_HOST }}/mediclab/tg_meme_bot"
  BOT_VERSION: ${{ github.event.release.tag_name }}

jobs:
  build-image:
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu-24.04
            platform: linux/amd64
          - name: ubuntu-24.04-arm
            platform: linux/arm64

    runs-on: ${{ matrix.os.name }}
    steps:
      - uses: actions/checkout@v4

      - name: Set environment
        run: |
          echo "APP_VERSION=$(cat Cargo.toml | grep -A3 '^\[package\]$' | grep -Po '(?<=^version = ")[^"]*(?=".*)' | tr -dc 0-9)"  >> $GITHUB_ENV
          echo "TAG_VERSION=$(echo ${{ github.event.release.tag_name }} | tr -dc 0-9)" >> $GITHUB_ENV
          platform=${{ matrix.os.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Check versions
        if: ${{ env.TAG_VERSION != env.APP_VERSION }}
        run: |
          echo "::error::Tag version = ${{ env.TAG_VERSION }} is not equals version from Cargo.toml = ${{ env.APP_VERSION }}"
          exit 1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_TITLE }}
            org.opencontainers.image.description=${{ env.IMAGE_DESCRIPTION }}
            org.opencontainers.image.vendor=mediclab
            org.opencontainers.image.authors=mediclab <m@mdlb.cc>

      - name: Login to Private Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_HOME_HOST }}
          username: ${{ secrets.DOCKER_HOME_LOGIN }}
          password: ${{ secrets.DOCKER_HOME_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile-prod
          build-args: "BOT_VERSION=${{ env.BOT_VERSION }}"
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true
          platforms: ${{ matrix.os.platform }}

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"          

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-24.04
    needs:
      - build-image
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to Private Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_HOME_HOST }}
          username: ${{ secrets.DOCKER_HOME_LOGIN }}
          password: ${{ secrets.DOCKER_HOME_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_TITLE }}
            org.opencontainers.image.description=${{ env.IMAGE_DESCRIPTION }}
            org.opencontainers.image.vendor=mediclab
            org.opencontainers.image.authors=mediclab <m@mdlb.cc>
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}            

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.IMAGE_NAME }}@sha256:%s ' *)