name: Docker Image CI

on:
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get version from Cargo.toml
        run: |
          echo "app_version=$(cat Cargo.toml | grep -A3 '^\[package\]$' | grep -Po '(?<=^version = ")[^"]*(?=".*)')" >> $GITHUB_ENV

      - name: Set versions to env
        run: |
          echo "check_version=$(echo ${{ env.app_version }} | tr -dc 0-9)"  >> $GITHUB_ENV
          echo "tag_version=$(echo ${{ github.event.release.tag_name }} | tr -dc 0-9)" >> $GITHUB_ENV

      - name: Check versions
        if: ${{ env.tag_version != env.check_version }}
        run: |
          echo "::error::Tag version = ${{ env.tag_version }} is not equals version from Cargo.toml = ${{ env.check_version }}"
          exit 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Private Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_HOME_HOST }}
          username: ${{ secrets.DOCKER_HOME_LOGIN }}
          password: ${{ secrets.DOCKER_HOME_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile-prod
          build-args: "BOT_VERSION=${{ env.app_version }}"
          push: true
          tags: "${{ secrets.DOCKER_HOME_HOST }}/mediclab/tg_meme_bot:latest,${{ secrets.DOCKER_HOME_HOST }}/mediclab/tg_meme_bot:${{ env.app_version }}"
          platforms: linux/amd64,linux/arm64

      - name: Curl for update stack on server
        continue-on-error: true
        run: |
          curl -fs -X POST ${{ secrets.CURL_WEBHOOK_URL }}