name: Check code

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build image
      run: docker build -t local -f Dockerfile-tests .
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    - name: Run linter
      run: docker run --rm -v $PWD:/app -v ~/.cargo:/root/.cargo -w /app local sh -c 'cargo check --verbose && cargo fmt --all -- --check && cargo clippy -- -D warnings'